# Basic Site Settings
locale                   : "en-US"
title                    : "R.W.Clayton's IDS Capstone"
title_separator          : "-"
url                      : https://rwclayton.github.io/UCF_IDS-Capstone/
